FROM node:alpine

ENV ASSET_NAME="concretefeedback"

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . .

RUN apk add --no-cache bash
RUN npm run boot

EXPOSE 4201

LABEL vf-OS=true
LABEL vf-OS.icon=img/2.png
LABEL vf-OS.urlprefixReplace=true
LABEL vf-OS.frontendUri="/concretefeedback"
LABEL vf-OS.name=concretefeedback
LABEL vf-OS.market.product=14
LABEL vf-OS.version.major=2
LABEL vf-OS.market.price=100
LABEL vf-OS.iconHDUr="/assets/img/concretefeedback.jpg"
LABEL vf-OS.boxshot="https://northeurope1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fknowledgebiz.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!fTR_MAuz-UW_FH6jVI_e4i1qEFOF_RlAqYqv1tjHDlhT6O5Sobx0Sapepqpn8D81%2Fitems%2F01PMB3CBSOP4LT7BAJNFELSXNC2YWIEABZ%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAva25vd2xlZGdlYml6LnNoYXJlcG9pbnQuY29tQGI5Y2MzMzZjLWQ0Y2UtNGFiNC1iYWYzLTJkNDk0ODA0NjBjYyIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE1NzI0NTI5NDIiLCJleHAiOiIxNTcyNDc0NTQyIiwiZW5kcG9pbnR1cmwiOiJZQWpmRjBnS1lnSHk2QTdwN2JHSmtoTzd0dzhqM0lBN0djM2MzbC9YRm1RPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE5IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJZemxtWVRFeU9XWXRaREJpWkMwNU1EQXdMV0V5WkdRdE56aGpZVGxpWmpRMU56TTAiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTXpBM1pqTTBOMlF0WWpNd1lpMDBOV1k1TFdKbU1UUXROMlZoTXpVME9HWmtaV1V5IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jZGYwYzY2ODdjYWI1NTdmYzQyMmIzMGQ3OGUzOWQxZTllMTFmOWQyM2Q5MTZiMGFlOWIxNjRiNWI1OGYyYjQ5ZCIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jZGYwYzY2ODdjYWI1NTdmYzQyMmIzMGQ3OGUzOWQxZTllMTFmOWQyM2Q5MTZiMGFlOWIxNjRiNWI1OGYyYjQ5ZCIsInNoYXJpbmdpZCI6ImZudnh4Y0kweGs2UFM2OHJqdTBYS1EiLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.NHdoSXBVc24yeGhFS0ZWZGZTR3VnZVdsTzZScnhFbEpNWEFrREpxQzVXMD0&encodeFailures=1&srcWidth=&srcHeight=&width=1919&height=913&action=Access"

CMD ["npm", "start"]
